# Configuration constants for the 4P1L tube preamp project

# SW Version
SW_VERSION = "1.2.5"

# Display Constants - Newhaven Display NHD-0420D3Z-NSW-BBW-V3
DISPLAY_ADDR = 0x28
REG_PREFIX = 0xFE
REG_POSITION = 0x45
REG_CLEAR = 0x51
REG_CONTRAST = 0x52
REG_BRIGHTNESS = 0x53
INITIAL_BRIGHTNESS = 0x02
STANDBY_BRIGHTNESS = 0x02
MAX_BRIGHTNESS = 0x08

DISPLAY_LINE1 = 0x00
DISPLAY_LINE2 = 0x40
DISPLAY_LINE3 = 0x14
DISPLAY_LINE4 = 0x54
MUTE_POSITION = 16
STANDBY_POSITION = 0x47

# State constants
STATE_STARTUP = 0
STATE_FILAMENT = 1
STATE_BPLUS = 2
STATE_OPERATE = 3
STATE_STANDBY = 4
STATE_TUBETIMER = 5
STATE_BALANCE = 6
STATE_TT_DISPLAY = 7
STATE_BRIGHTNESS = 8

# MPC9808 Temperature Sensor Constants
MPC9808_ADDR = 0x18
TEMP_DATA_REG = 0x05

# Muses 72320 Volume Chip Constants
LEFT_LSB_0 = 0x00
LEFT_LSB_1 = 0x20
RIGHT_LSB_0 = 0x01
RIGHT_LSB_1 = 0x21
MUSES_ATTEN_0 = 0x10

# Relay Constants - Panasonic DS2E-SL2-DC12V
REL_ON = 1
REL_OFF = 0
REL_LATCH_TIME = 20

REL_FILAMENT = 0
REL_BPLUS = 1
REL_MUTE = 2
REL_SEL1SET = 3
REL_SEL1RESET = 4
REL_SEL2SET = 5
REL_SEL2RESET = 6
REL_SEL3SET = 7
REL_SEL3RESET = 8
REL_SEL4SET = 9
REL_SEL4RESET = 10
REL_SEL5SET = 11
REL_SEL5RESET = 12

# Product Constants
MAX_VOLUME = 64
MAX_BALANCE = 6

MUTE_ON = 0
MUTE_OFF = 1
MUTE_ST_OFF = 0
MUTE_ST_ON = 1

OPERATE_ON = 0
OPERATE_OFF = 1
OPERATE_ST_OFF = 0
OPERATE_ST_ON = 1

PB_PUSHED = 0
PB_RELEASED = 1

SELECT_NONE = 0
SELECT_STREAMING = 1
SELECT_CD = 2
SELECT_PHONO = 3
SELECT_AUX1 = 4
SELECT_AUX2 = 5

# Messages to pass on the Queue
NULL_MESSAGE = 0
L_PB_PUSHED = 1
R_PB_PUSHED = 2
VOL_KNOB_CCW = 3
VOL_KNOB_CW = 4
SEL_KNOB_CCW = 5
SEL_KNOB_CW = 6
SW_MUTE_ON = 7
SW_MUTE_OFF = 8
SW_OPERATE_ON = 9
SW_OPERATE_OFF = 10
UPDATE_TEMP = 11
SECOND_BEAT = 12
MINUTE_BEAT = 13

SPLASH_DELAY = 3
FILAMENT_DELAY = 3
BPLUS_DELAY = 3
